name: Create gitmoji label
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of release'
        required: true
jobs:
  create-gitmoji-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      repository-projects: read
    steps:
      - name: Create release
        uses: georgepstaylor/gitmoji-release-action@v0.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
